name: Deploy Infrastructure
'on':
  push:
    branches:
      - master
    paths:
      - terraform/**
      - .github/workflows/deploy-infrastructure.yml
env:
  PROJECT_ID: 2c8e42bc-44de-44b1-b2c9-966dc69032b6
  WEBHOOK_SECRET: MHv7y4zE9pXG2wqAFU1cJRt3NZmLkoBd
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-north-1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
            -input=false \
            -out=tfplan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply \
            -input=false \
            tfplan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_website_files_path: ${{ github.workspace }}/website
      - name: Store Outputs in SSM
        run: |
          cd ./terraform
          # Get raw outputs without quotes
          S3_BUCKET=$(terraform output s3_bucket_name | grep -oE '".*"' | tr -d '"' | head -1)
          CF_ID=$(terraform output cloudfront_distribution_id | grep -oE '".*"' | tr -d '"' | head -1)
          CLOUDFRONT_URL=$(terraform output cloudfront_url | grep -oE '".*"' | tr -d '"' | head -1)
          APPRUNNER_URL=$(terraform output apprunner_service_url | grep -oE '".*"' | tr -d '"' | head -1)

          echo "Stored S3 Bucket: $S3_BUCKET"
          echo "Stored CloudFront ID: $CF_ID"
          aws ssm put-parameter --name "/app/s3-bucket" --value "$S3_BUCKET" --type String --overwrite
          aws ssm put-parameter --name "/app/cf-id" --value "$CF_ID" --type String --overwrite
          aws ssm put-parameter --name "/app/cloudfront_url" --value "$CLOUDFRONT_URL" --type String --overwrite
          aws ssm put-parameter --name "/app/apprunner_url" --value "$APPRUNNER_URL" --type String --overwrite
          echo "Stored S3 Bucket: $S3_BUCKET"
          echo "Stored CloudFront ID: $CF_ID"
          echo "Stored CloudFront URL: $CLOUDFRONT_URL"
          echo "Stored AppRunner URL: $APPRUNNER_URL"
      - name: Notify infrastructure provisioning webhook if successful
        if: success()
        run: |
          cd ./terraform
          # Get raw outputs without quotes
          S3_BUCKET=$(terraform output s3_bucket_name | grep -oE '".*"' | tr -d '"' | head -1)
          CF_ID=$(terraform output cloudfront_distribution_id | grep -oE '".*"' | tr -d '"' | head -1)
          CLOUDFRONT_URL=$(terraform output cloudfront_url | grep -oE '".*"' | tr -d '"' | head -1)
          APPRUNNER_URL=$(terraform output apprunner_service_url | grep -oE '".*"' | tr -d '"' | head -1)
          RDS_ENDPOINT=$(terraform output rds_endpoint | grep -oE '".*"' | tr -d '"' | head -1)

          aws ssm put-parameter --name "/app/s3-bucket" --value "$S3_BUCKET" --type String --overwrite
          aws ssm put-parameter --name "/app/cf-id" --value "$CF_ID" --type String --overwrite
          aws ssm put-parameter --name "/app/cloudfront_url" --value "$CLOUDFRONT_URL" --type String --overwrite
          aws ssm put-parameter --name "/app/apprunner_url" --value "$APPRUNNER_URL" --type String --overwrite
          aws ssm put-parameter --name "/app/rds_endpoint" --value "$RDS_ENDPOINT" --type String --overwrite
          curl -X POST https://8f9a-185-107-56-163.ngrok-free.app/api/deployment/webhook/advance/success/infrastructure \
            -H "Content-Type: application/json" \
            -H "x-webhook-secret: ${{ env.WEBHOOK_SECRET }}" \
            -d '{
              "projectId": "${{ env.PROJECT_ID }}",
              "frontendUrl": "'"$CLOUDFRONT_URL"'",
              "backendUrl": "'"$APPRUNNER_URL"'",
              "databaseUrl": "'"$RDS_ENDPOINT"'",
              "s3bucketUrl": "'"$S3_BUCKET"'",
              "message": "Infrastructure provisioning succeeded",
              "status": "success"
          }'
      - name: Notify infrastructure provisioning webhook if failed
        if: failure()
        run: "WORKFLOW_URL=\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"\n\ncurl -X POST  https://8f9a-185-107-56-163.ngrok-free.app/api/deployment/webhook/advance/failure/infrastructure \\\n  -H \"Content-Type: application/json\" \\\n  -H \"x-webhook-secret: ${{ secrets.WEBHOOK_SECRET }}\" \\\n  -d '{\n    \"projectId\": \"${{ env.PROJECT_ID }}\",\n    \"workflowUrl\": \"'\"$WORKFLOW_URL\"'\",\n    \"message\": \"Infrastructure provisioning failed\",\n    \"status\": \"failure\"\n\_}'\n"
