name: Deploy to EC2

on:
  push:
    branches: [medium]

env:
  DOCKER_COMPOSE_VERSION: 1.29.2
  PROJECT_NAME: "three"
  DOMAIN: craftapp
  PROJECT_DIR: "/home/ubuntu/app/three"
  POSTGRES_DATA_DIR: "/opt/three/postgres-data"
  CPU_LIMIT: "1000"
  MEMORY_LIMIT: "2097152"
  SWAP_LIMIT: "2684354560"
  CPU_SET: "0-1"
  WEBHOOK_SECRET: "MHv7y4zE9pXG2wqAFU1cJRt3NZmLkoBd"
  PROJECT_ID: "2c8e42bc-44de-44b1-b2c9-966dc69032b6"
  OOM_SCORE_ADJ: "-500"
  STORAGE_LIMIT_GB: "2"
  CENTRAL_NGINX_DIR: "/home/ubuntu/app/central-nginx"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './'
          target: '${{ env.PROJECT_DIR }}'

      - name: Update central-nginx networks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd "${{ env.PROJECT_DIR }}"
            sudo chmod +x devops/update_compose.sh
            devops/update_compose.sh "${{ env.PROJECT_NAME }}"

      - name: Run nginx.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd "${{ env.PROJECT_DIR }}"
            chmod +x devops/nginx-setup.sh
            devops/nginx-setup.sh "${{ env.PROJECT_NAME }}" "keraamzabih@gmail.com" "44.203.250.84" "craftapp" "ai"

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            sudo mkdir -p "${{ env.POSTGRES_DATA_DIR }}"
            sudo chown -R 1000:1000 "${{ env.POSTGRES_DATA_DIR }}"
            sudo chmod -R 755 "/opt/${{ env.PROJECT_NAME }}"
            DEVICE_ID=$(lsblk -d -o MAJ:MIN | awk 'NR==2{print $1}')
            cd "${{ env.PROJECT_DIR }}"
            sudo chmod +x devops/init-db.sh
            sudo chmod +x devops/cgroup-setup.sh
            sudo chmod 644 frontend/.env
            sudo chmod 644 backend/.env
            sudo chmod 644 .env
            ./devops/cgroup-setup.sh "${{ env.PROJECT_NAME }}" "${{ env.CPU_LIMIT }}" "${{ env.MEMORY_LIMIT }}" "${{ env.STORAGE_LIMIT_GB }}" "$DEVICE_ID"
            docker-compose down || true
            docker system prune -f
            docker-compose up -d --build
            sleep 360
            if docker exec central-nginx nginx -t; then
              docker exec central-nginx nginx -s reload
              echo "✅ NGINX reloaded successfully"
            else
              echo "❌ NGINX configuration test failed"
              exit 1
            fi
            services=("frontend-1" "backend-1" "postgres-1")

            for service in "${services[@]}"; do
              container="${{ env.PROJECT_NAME }}-${service}"
              if docker ps | grep -q "$container"; then
                pid=$(docker inspect -f '{{.State.Pid}}' "$container")
                echo "Assigning $container (PID: $pid) to cgroup"
                echo "$pid" | sudo tee "/sys/fs/cgroup/${{ env.PROJECT_NAME }}/cgroup.procs"
              else
                echo "Container $container not found!"
                exit 1
              fi
            done

            echo "Current cgroup processes:"
            cat /sys/fs/cgroup/${{ env.PROJECT_NAME }}/cgroup.procs
            echo "Container stats:"
            docker stats --no-stream

      - name: Notify deployment webhook if successful
        if: success()
        run: |
          curl -X POST https://6d6c-149-54-36-243.ngrok-free.app/api/deployment/webhook/success \
            -H "Content-Type: application/json" \
            -H "x-webhook-secret: ${{ env.WEBHOOK_SECRET }}" \
            -d '{
              "projectId": "${{ env.PROJECT_ID }}",
              "message": "Production deployment succeeded",
              "status": "success"
            }'

      - name: Notify deployment webhook if failed
        if: failure()
        run: |
          curl -X POST https://6d6c-149-54-36-243.ngrok-free.app/api/deployment/webhook/failure \
            -H "Content-Type: application/json" \
            -H "x-webhook-secret: ${{ env.WEBHOOK_SECRET }}" \
            -d '{
              "projectId": "${{ env.PROJECT_ID }}",
              "message": "Production deployment failed",
              "status": "failure"
            }'
