name: Test and Build Frontend
'on':
  push:
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/test-frontend.yml
  workflow_run:
    workflows:
      - Deploy Infrastructure
    types:
      - completed
env:
  PROJECT_ID: 2c8e42bc-44de-44b1-b2c9-966dc69032b6
  WEBHOOK_SECRET: MHv7y4zE9pXG2wqAFU1cJRt3NZmLkoBd
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
      - name: Build application
        run: |
          cd frontend
          npm run build
      - name: Notify infrastructure provisioning webhook if successful
        if: success()
        run: |
          curl -X POST  https://7ec7-185-107-80-121.ngrok-free.app/api/deployment/webhook/advance/success/test \
            -H "Content-Type: application/json" \
            -H "x-webhook-secret: ${{ env.WEBHOOK_SECRET }}" \
            -d '{
              "projectId": "${{ env.PROJECT_ID }}",
              "message": "Infrastructure provisioning succeeded",
              "status": "success"
            }'
      - name: Notify infrastructure provisioning webhook if failed
        if: failure()
        run: "WORKFLOW_URL=\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"\n\ncurl -X POST  https://7ec7-185-107-80-121.ngrok-free.app/api/deployment/webhook/advance/failure/test \\\n  -H \"Content-Type: application/json\" \\\n  -H \"x-webhook-secret: ${{ secrets.WEBHOOK_SECRET }}\" \\\n  -d '{\n    \"projectId\": \"${{ env.PROJECT_ID }}\",\n    \"workflowUrl\": \"'\"$WORKFLOW_URL\"'\",\n    \"message\": \"Infrastructure provisioning failed\",\n\_}'\n"
